//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationVersionDetails
    {
        public int Id { get; set; }
        public System.Guid ApplicationVersionId { get; set; }
        public System.Guid InnerEntryInEntryId { get; set; }
        public int InnerEntryInEntryPriority { get; set; }
    
        public virtual ApplicationVersion ApplicationVersion { get; set; }
        public virtual InnerEntryInEntry InnerEntryInEntry { get; set; }
    }
}
