//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttMarks
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public int AttSubjectId { get; set; }
        public int Value { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual AttSubject AttSubject { get; set; }
        public virtual Person Person { get; set; }
    }
}
