//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FirstWave
    {
        public System.Guid AbiturientId { get; set; }
        public int SortNum { get; set; }
        public bool IsCel { get; set; }
        public bool IsCrimea { get; set; }
        public bool IsQuota { get; set; }
    }
}
