//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FirstWaveGreen
    {
        public System.Guid AbiturientId { get; set; }
        public bool IsNew { get; set; }
        public Nullable<System.Guid> CalculationId { get; set; }
        public int Position { get; set; }
    }
}
