//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_FirstWaveGreen
    {
        public System.Guid AbiturientId { get; set; }
        public bool IsNew { get; set; }
        public Nullable<System.Guid> CalculationId { get; set; }
    }
}
