//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocInventory
    {
        public System.Guid AbiturientId { get; set; }
        public int AbitDocId { get; set; }
        public string Comment { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual AbitDoc AbitDoc { get; set; }
        public virtual Abiturient Abiturient { get; set; }
    }
}
