//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocInventory
    {
        public System.Guid AbiturientId { get; set; }
        public int AbitDocId { get; set; }
        public string Comment { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual AbitDoc AbitDoc { get; set; }
        public virtual Abiturient Abiturient { get; set; }
    }
}
