//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgeCertificate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EgeCertificate()
        {
            this.EgeMark = new HashSet<EgeMark>();
            this.Mark = new HashSet<Mark>();
        }
    
        public System.Guid Id { get; set; }
        public string Number { get; set; }
        public string PrintNumber { get; set; }
        public string Year { get; set; }
        public System.Guid PersonId { get; set; }
        public string NewFIO { get; set; }
        public int FBSStatusId { get; set; }
        public string FBSComment { get; set; }
        public bool IsImported { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public Nullable<bool> NoNumber { get; set; }
        public System.DateTime ImportDate { get; set; }
    
        public virtual FBSStatus FBSStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EgeMark> EgeMark { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark> Mark { get; set; }
    }
}
