//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgeMark
    {
        public System.Guid Id { get; set; }
        public int Value { get; set; }
        public int EgeExamNameId { get; set; }
        public System.Guid EgeCertificateId { get; set; }
        public bool IsAppeal { get; set; }
        public bool IsCurrent { get; set; }
    
        public virtual EgeCertificate EgeCertificate { get; set; }
        public virtual EgeExamName EgeExamName { get; set; }
    }
}
