//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class EgeToExam
    {
        public int Id { get; set; }
        public int EgeExamNameId { get; set; }
        public Nullable<int> ExamId { get; set; }
    
        public virtual EgeExamName EgeExamName { get; set; }
        public virtual Exam Exam { get; set; }
    }
}
