//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryToCompetitiveGroup
    {
        public System.Guid Id { get; set; }
        public System.Guid EntryId { get; set; }
        public System.Guid CompetitiveGroupId { get; set; }
        public Nullable<System.Guid> CompetitiveGroupItemId { get; set; }
    
        public virtual CompetitiveGroup CompetitiveGroup { get; set; }
        public virtual Entry Entry { get; set; }
    }
}
