//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryToCompetitiveGroup
    {
        public System.Guid Id { get; set; }
        public System.Guid EntryId { get; set; }
        public System.Guid CompetitiveGroupId { get; set; }
        public Nullable<System.Guid> CompetitiveGroupItemId { get; set; }
    
        public virtual CompetitiveGroup CompetitiveGroup { get; set; }
        public virtual Entry Entry { get; set; }
    }
}
