//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamsVedHistory
    {
        public System.Guid ExamsVedId { get; set; }
        public System.Guid PersonId { get; set; }
        public Nullable<int> PersonVedNumber { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public Nullable<decimal> OralMark { get; set; }
        public Nullable<decimal> AppealMark { get; set; }
        public Nullable<decimal> OralAppealMark { get; set; }
        public string ExaminerName { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual ExamsVed ExamsVed { get; set; }
        public virtual Person Person { get; set; }
    }
}
