//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamInEntryBlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamInEntryBlock()
        {
            this.ExamInEntryBlockUnit = new HashSet<ExamInEntryBlockUnit>();
            this.InnerEntryInEntry = new HashSet<InnerEntryInEntry>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid EntryId { get; set; }
        public string Name { get; set; }
        public bool IsProfil { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public bool IsGosLine { get; set; }
        public bool IsCrimea { get; set; }
        public byte OrderNumber { get; set; }
        public Nullable<System.Guid> ParentExamInEntryBlockId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamInEntryBlockUnit> ExamInEntryBlockUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InnerEntryInEntry> InnerEntryInEntry { get; set; }
    }
}
