//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamsVedMarkDetails
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ExamsVedHistoryMarkId { get; set; }
        public string ExaminerName { get; set; }
        public Nullable<decimal> MarkValue { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual ExamsVedHistoryMark ExamsVedHistoryMark { get; set; }
    }
}
