//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamsVedHistoryMark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamsVedHistoryMark()
        {
            this.ExamsVedMarkDetails = new HashSet<ExamsVedMarkDetails>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ExamsVedHistoryId { get; set; }
        public Nullable<int> ExamsVedMarkTypeId { get; set; }
        public Nullable<decimal> MarkValue { get; set; }
        public Nullable<decimal> AppealMarkValue { get; set; }
    
        public virtual ExamsVedMarkType ExamsVedMarkType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamsVedMarkDetails> ExamsVedMarkDetails { get; set; }
    }
}
