//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamsVedMarkDetails
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ExamsVedHistoryMarkId { get; set; }
        public string ExaminerName { get; set; }
        public Nullable<decimal> MarkValue { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Comment { get; set; }
    
        public virtual ExamsVedHistoryMark ExamsVedHistoryMark { get; set; }
    }
}
