//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamsVedHistory
    {
        public System.Guid ExamsVedId { get; set; }
        public System.Guid PersonId { get; set; }
        public Nullable<int> PersonVedNumber { get; set; }
        public Nullable<decimal> Mark { get; set; }
        public Nullable<decimal> OralMark { get; set; }
        public Nullable<decimal> AppealMark { get; set; }
        public Nullable<decimal> OralAppealMark { get; set; }
        public string ExaminerName { get; set; }
    
        public virtual ExamsVed ExamsVed { get; set; }
        public virtual Person Person { get; set; }
    }
}
