//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamsVedRoom
    {
        public System.Guid Id { get; set; }
        public System.Guid ExamsVedId { get; set; }
        public string RoomNumber { get; set; }
        public int Number { get; set; }
    }
}
