//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamInEntryBlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamInEntryBlock()
        {
            this.ExamInEntryBlockUnit = new HashSet<ExamInEntryBlockUnit>();
            this.InnerEntryInEntry = new HashSet<InnerEntryInEntry>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid EntryId { get; set; }
        public string Name { get; set; }
        public bool IsProfil { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public bool IsGosLine { get; set; }
        public bool IsCrimea { get; set; }
        public byte OrderNumber { get; set; }
        public Nullable<System.Guid> ParentExamInEntryBlockId { get; set; }
        public Nullable<int> Grade5MarkMin { get; set; }
        public Nullable<int> Grade5MarkMax { get; set; }
        public Nullable<int> Grade4MarkMin { get; set; }
        public Nullable<int> Grade4MarkMax { get; set; }
        public Nullable<int> Grade3MarkMin { get; set; }
        public Nullable<int> Grade3MarkMax { get; set; }
        public bool IsNotInTotalSum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamInEntryBlockUnit> ExamInEntryBlockUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InnerEntryInEntry> InnerEntryInEntry { get; set; }
        public virtual Entry Entry { get; set; }
    }
}
