//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamsVedHistoryMark
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamsVedHistoryMark()
        {
            this.ExamsVedMarkDetails = new HashSet<ExamsVedMarkDetails>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> ExamsVedHistoryId { get; set; }
        public Nullable<int> ExamsVedMarkTypeId { get; set; }
        public Nullable<decimal> MarkValue { get; set; }
        public Nullable<decimal> AppealMarkValue { get; set; }
        public Nullable<bool> MarkIsChecked { get; set; }
    
        public virtual ExamsVedMarkType ExamsVedMarkType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamsVedMarkDetails> ExamsVedMarkDetails { get; set; }
    }
}
