//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamsVed
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamsVed()
        {
            this.ExaminerInExamsVed = new HashSet<ExaminerInExamsVed>();
            this.ExamsVedHistory = new HashSet<ExamsVedHistory>();
        }
    
        public System.Guid Id { get; set; }
        public int Number { get; set; }
        public int StudyLevelGroupId { get; set; }
        public int FacultyId { get; set; }
        public Nullable<int> StudyBasisId { get; set; }
        public System.DateTime Date { get; set; }
        public int ExamId { get; set; }
        public bool IsLocked { get; set; }
        public bool IsLoad { get; set; }
        public bool IsAdd { get; set; }
        public Nullable<int> AddCount { get; set; }
        public string ExaminerAccount { get; set; }
        public Nullable<int> ExaminerCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExaminerInExamsVed> ExaminerInExamsVed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamsVedHistory> ExamsVedHistory { get; set; }
    }
}
