//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExaminerInExamsVed
    {
        public System.Guid ExamsVedId { get; set; }
        public string ExaminerAccount { get; set; }
        public Nullable<bool> IsMain { get; set; }
    
        public virtual ExamsVed ExamsVed { get; set; }
    }
}
