//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extAbitMarksSumAG
    {
        public System.Guid Id { get; set; }
        public int StudyFormId { get; set; }
        public int StudyBasisId { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public Nullable<int> TotalCount { get; set; }
    }
}
