//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extAbitMarksSumAG
    {
        public System.Guid Id { get; set; }
        public int StudyFormId { get; set; }
        public int StudyBasisId { get; set; }
        public Nullable<decimal> TotalSum { get; set; }
        public Nullable<int> TotalCount { get; set; }
    }
}
