//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extAbitAllAdditionalAchievements
    {
        public System.Guid AbiturientId { get; set; }
        public string AchievementType { get; set; }
        public Nullable<int> AchievementTypeId { get; set; }
        public Nullable<int> Mark { get; set; }
    }
}
