//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extEntry
    {
        public System.Guid Id { get; set; }
        public int FacultyId { get; set; }
        public int LicenseProgramId { get; set; }
        public string LicenseProgramName { get; set; }
        public string LicenseProgramCode { get; set; }
        public int ObrazProgramId { get; set; }
        public string ObrazProgramName { get; set; }
        public string ObrazProgramNumber { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public int ProfileId { get; set; }
        public string ProfileName { get; set; }
        public int StudyBasisId { get; set; }
        public int StudyFormId { get; set; }
        public int StudyLevelId { get; set; }
        public Nullable<System.Guid> StudyPlanId { get; set; }
        public string StudyPlanNumber { get; set; }
        public string ProgramModeShortName { get; set; }
        public bool IsSecond { get; set; }
        public Nullable<int> KCP { get; set; }
        public string FacultyName { get; set; }
        public string StudyBasisName { get; set; }
        public string StudyFormName { get; set; }
        public string StudyLevelName { get; set; }
        public bool IsClosed { get; set; }
        public int StudyLevelGroupId { get; set; }
        public string ObrazProgramNameEx { get; set; }
        public string FacultyAcr { get; set; }
        public Nullable<int> KCPCel { get; set; }
        public bool IsReduced { get; set; }
        public bool IsParallel { get; set; }
        public string QualificationCode { get; set; }
        public string StudyLevelFISName { get; set; }
        public string ObrazProgramPrintName { get; set; }
        public Nullable<int> KCPQuota { get; set; }
        public int AggregateGroupId { get; set; }
        public string AggregateGroupName { get; set; }
        public bool IsForeign { get; set; }
        public bool IsCrimea { get; set; }
        public string StudyLevelGroupName { get; set; }
        public System.DateTime DateOfClose { get; set; }
        public System.DateTime DateOfStart { get; set; }
        public Nullable<System.DateTime> DateStartEduc { get; set; }
        public Nullable<System.DateTime> DateFinishEduc { get; set; }
        public Nullable<System.Guid> ParentEntryId { get; set; }
        public string FacultyCode { get; set; }
        public Nullable<int> StudyLevelGroupUpperCategoryId { get; set; }
        public string AggregateGroupAcronym { get; set; }
    }
}
