//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extEntry
    {
        public System.Guid Id { get; set; }
        public int FacultyId { get; set; }
        public int LicenseProgramId { get; set; }
        public string LicenseProgramName { get; set; }
        public string LicenseProgramCode { get; set; }
        public int ObrazProgramId { get; set; }
        public string ObrazProgramName { get; set; }
        public string ObrazProgramNumber { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public int ProfileId { get; set; }
        public string ProfileName { get; set; }
        public int StudyBasisId { get; set; }
        public int StudyFormId { get; set; }
        public int StudyLevelId { get; set; }
        public Nullable<System.Guid> StudyPlanId { get; set; }
        public string StudyPlanNumber { get; set; }
        public string ProgramModeShortName { get; set; }
        public bool IsSecond { get; set; }
        public Nullable<int> KCP { get; set; }
        public string FacultyName { get; set; }
        public string StudyBasisName { get; set; }
        public string StudyFormName { get; set; }
        public string StudyLevelName { get; set; }
        public bool IsClosed { get; set; }
        public int StudyLevelGroupId { get; set; }
        public string ObrazProgramNameEx { get; set; }
        public string FacultyAcr { get; set; }
        public Nullable<int> KCPCel { get; set; }
        public bool IsReduced { get; set; }
        public bool IsParallel { get; set; }
        public string QualificationCode { get; set; }
        public string StudyLevelFISName { get; set; }
        public string ObrazProgramPrintName { get; set; }
        public Nullable<int> KCPQuota { get; set; }
        public int AggregateGroupId { get; set; }
        public string AggregateGroupName { get; set; }
        public bool IsForeign { get; set; }
        public bool IsCrimea { get; set; }
        public string StudyLevelGroupName { get; set; }
        public System.DateTime DateOfClose { get; set; }
        public System.DateTime DateOfStart { get; set; }
        public Nullable<System.DateTime> DateStartEduc { get; set; }
        public Nullable<System.DateTime> DateFinishEduc { get; set; }
        public Nullable<System.Guid> ParentEntryId { get; set; }
        public string FacultyCode { get; set; }
        public Nullable<int> StudyLevelGroupUpperCategoryId { get; set; }
        public string AggregateGroupAcronym { get; set; }
        public string StudyFormFISName { get; set; }
        public Nullable<int> LicenseProgram_FISID { get; set; }
        public Nullable<int> StudyLevel_FISID { get; set; }
        public Nullable<int> StudyBasis_FISID { get; set; }
        public Nullable<int> StudyForm_FISID { get; set; }
        public string NormativePeriod { get; set; }
        public string QualificationName { get; set; }
        public string FacultyDirectionName { get; set; }
        public string ExamName1 { get; set; }
        public string ExamName2 { get; set; }
        public string ExamName3 { get; set; }
        public string ExamName4 { get; set; }
        public string ExamName5 { get; set; }
    }
}
