//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extExamInEntry
    {
        public System.Guid Id { get; set; }
        public System.Guid EntryId { get; set; }
        public int ExamId { get; set; }
        public bool IsProfil { get; set; }
        public Nullable<decimal> EgeMin { get; set; }
        public int ExamNameId { get; set; }
        public bool IsAdditional { get; set; }
        public string ExamName { get; set; }
        public int FacultyId { get; set; }
        public int LicenseProgramId { get; set; }
        public int ObrazProgramId { get; set; }
        public int ProfileId { get; set; }
        public int StudyBasisId { get; set; }
        public int StudyFormId { get; set; }
        public int StudyLevelId { get; set; }
        public int StudyLevelGroupId { get; set; }
        public string ExamDefName { get; set; }
        public bool IsSecond { get; set; }
        public bool IsReduced { get; set; }
        public bool IsParallel { get; set; }
        public byte OrderNumber { get; set; }
        public bool IsCrimea { get; set; }
        public bool IsGosLine { get; set; }
        public Nullable<System.Guid> ParentExamInEntryBlockId { get; set; }
        public bool IsForeign { get; set; }
        public System.Guid ExamInEntryBlockId { get; set; }
    }
}
