//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extExamsVed
    {
        public System.Guid Id { get; set; }
        public int Number { get; set; }
        public int StudyLevelGroupId { get; set; }
        public int FacultyId { get; set; }
        public Nullable<int> StudyBasisId { get; set; }
        public System.DateTime Date { get; set; }
        public int ExamId { get; set; }
        public bool IsLocked { get; set; }
        public bool IsLoad { get; set; }
        public bool IsAddVed { get; set; }
        public Nullable<int> AddCount { get; set; }
        public int ExamNameId { get; set; }
        public bool IsAdditional { get; set; }
        public string ExamName { get; set; }
        public string ExamAcronym { get; set; }
        public string StudyBasisName { get; set; }
        public string StudyBasisAcr { get; set; }
        public string FacultyName { get; set; }
    }
}
