//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extEgeMark
    {
        public System.Guid Id { get; set; }
        public int Value { get; set; }
        public int EgeExamNameId { get; set; }
        public System.Guid EgeCertificateId { get; set; }
        public bool IsAppeal { get; set; }
        public bool IsCurrent { get; set; }
        public string EgeExamName { get; set; }
        public string Number { get; set; }
        public System.Guid PersonId { get; set; }
        public string Year { get; set; }
        public string FISName { get; set; }
        public int FBSStatusId { get; set; }
    }
}
