//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extFBSStatus
    {
        public string FBSStatus { get; set; }
        public Nullable<int> FBSStatusId { get; set; }
        public System.Guid PersonId { get; set; }
        public string Surname { get; set; }
    }
}
