//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extOlympBook
    {
        public System.Guid Id { get; set; }
        public int OlympTypeId { get; set; }
        public int OlympNameId { get; set; }
        public int OlympSubjectId { get; set; }
        public int OlympLevelId { get; set; }
        public string OlympNameName { get; set; }
        public string OlympLevelName { get; set; }
        public string OlympSubjectName { get; set; }
        public string OlympTypeName { get; set; }
        public string Number { get; set; }
        public int OlympYear { get; set; }
        public int OlympProfileId { get; set; }
        public string OlympProfileName { get; set; }
        public string OlympicID { get; set; }
    }
}
