//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extPersonAll
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Barcode { get; set; }
        public int Num { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string Surname { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public int PassportTypeId { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public string PassportAuthor { get; set; }
        public Nullable<System.DateTime> PassportDate { get; set; }
        public bool Sex { get; set; }
        public Nullable<int> CountryId { get; set; }
        public int NationalityId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string Phone { get; set; }
        public string Mobiles { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Flat { get; set; }
        public string CodeReal { get; set; }
        public string Korpus { get; set; }
        public string CityReal { get; set; }
        public string StreetReal { get; set; }
        public string HouseReal { get; set; }
        public string KorpusReal { get; set; }
        public string FlatReal { get; set; }
        public Nullable<bool> HostelAbit { get; set; }
        public Nullable<bool> HasAssignToHostel { get; set; }
        public Nullable<int> HostelFacultyId { get; set; }
        public Nullable<int> ExamPassFacultyId { get; set; }
        public Nullable<bool> HasExamPass { get; set; }
        public Nullable<bool> IsExcellent { get; set; }
        public Nullable<int> LanguageId { get; set; }
        public Nullable<int> SchoolTypeId { get; set; }
        public string SchoolCity { get; set; }
        public string SchoolName { get; set; }
        public string SchoolNum { get; set; }
        public Nullable<int> SchoolExitYear { get; set; }
        public Nullable<int> CountryEducId { get; set; }
        public string AttestatSeries { get; set; }
        public string AttestatNum { get; set; }
        public string DiplomSeries { get; set; }
        public string DiplomNum { get; set; }
        public Nullable<double> SchoolAVG { get; set; }
        public string HighEducation { get; set; }
        public string HEProfession { get; set; }
        public string HEQualification { get; set; }
        public Nullable<int> HEStudyFormId { get; set; }
        public Nullable<int> HEEntryYear { get; set; }
        public Nullable<int> HEExitYear { get; set; }
        public string HEWork { get; set; }
        public string MSVuz { get; set; }
        public Nullable<int> MSStudyFormId { get; set; }
        public string MSCourse { get; set; }
        public string Stag { get; set; }
        public string WorkPlace { get; set; }
        public Nullable<int> Privileges { get; set; }
        public string PassportCode { get; set; }
        public string PersonalCode { get; set; }
        public string PersonInfo { get; set; }
        public string ExtraInfo { get; set; }
        public string ScienceWork { get; set; }
        public string PersonNum { get; set; }
        public string FIO { get; set; }
        public string PassportData { get; set; }
        public string EducDocument { get; set; }
        public string HostelFacultyAcr { get; set; }
        public string CountryName { get; set; }
        public string NationalityName { get; set; }
        public string RegionName { get; set; }
        public string HostelFacultyName { get; set; }
        public Nullable<bool> StartEnglish { get; set; }
        public Nullable<int> EnglishMark { get; set; }
        public Nullable<bool> EgeInSPbgu { get; set; }
        public Nullable<int> VAKPublCount { get; set; }
        public Nullable<int> TotalPublCount { get; set; }
        public Nullable<bool> CompetitionWinner { get; set; }
        public Nullable<bool> HasGrant { get; set; }
        public Nullable<bool> IsEqual { get; set; }
        public Nullable<bool> HostelEduc { get; set; }
        public string SNILS { get; set; }
        public Nullable<int> RegionEducId { get; set; }
        public string KladrCode { get; set; }
        public string EqualDocumentNumber { get; set; }
        public Nullable<int> ForeignNationalityId { get; set; }
        public Nullable<int> ForeignCountryId { get; set; }
        public Nullable<bool> HasTRKI { get; set; }
        public string TRKICertificateNumber { get; set; }
        public Nullable<int> ForeignCountryEducId { get; set; }
    }
}
