//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extProtocol
    {
        public System.Guid Id { get; set; }
        public System.Guid AbiturientId { get; set; }
        public bool Excluded { get; set; }
        public Nullable<System.Guid> ExcludeProtocolId { get; set; }
        public Nullable<int> EntryHeaderId { get; set; }
        public int StudyLevelGroupId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> LicenseProgramId { get; set; }
        public int StudyFormId { get; set; }
        public Nullable<int> StudyBasisId { get; set; }
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public int ProtocolTypeId { get; set; }
        public string Reason { get; set; }
        public bool IsOld { get; set; }
        public Nullable<System.Guid> ParentProtocolId { get; set; }
        public bool IsSecond { get; set; }
        public bool IsListener { get; set; }
        public string ProtocolTypeName { get; set; }
        public bool IsParallel { get; set; }
        public bool IsReduced { get; set; }
        public string Faculty { get; set; }
        public string StudyBasis { get; set; }
        public string StudyForm { get; set; }
        public string FacultyAcr { get; set; }
        public string FacultyRodName { get; set; }
        public string FacultyDatName { get; set; }
        public string StudyFormAcr { get; set; }
        public string StudyFormRodName { get; set; }
        public System.Guid ProtocolHistoryId { get; set; }
        public bool IsForeign { get; set; }
        public Nullable<int> StudyLevelGroupUpperCategoryId { get; set; }
    }
}
