//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class extPerson
    {
        public System.Guid Id { get; set; }
        public Nullable<int> Barcode { get; set; }
        public int Num { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public string Surname { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public int PassportTypeId { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public string PassportAuthor { get; set; }
        public Nullable<System.DateTime> PassportDate { get; set; }
        public bool Sex { get; set; }
        public int CountryId { get; set; }
        public int NationalityId { get; set; }
        public int RegionId { get; set; }
        public string Phone { get; set; }
        public string Mobiles { get; set; }
        public string Email { get; set; }
        public string Code { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Flat { get; set; }
        public string CodeReal { get; set; }
        public string Korpus { get; set; }
        public string CityReal { get; set; }
        public string StreetReal { get; set; }
        public string HouseReal { get; set; }
        public string KorpusReal { get; set; }
        public string FlatReal { get; set; }
        public bool HostelAbit { get; set; }
        public bool HasAssignToHostel { get; set; }
        public Nullable<int> HostelFacultyId { get; set; }
        public Nullable<int> ExamPassFacultyId { get; set; }
        public bool HasExamPass { get; set; }
        public int LanguageId { get; set; }
        public string MSVuz { get; set; }
        public Nullable<int> MSStudyFormId { get; set; }
        public string MSCourse { get; set; }
        public string Stag { get; set; }
        public string WorkPlace { get; set; }
        public int Privileges { get; set; }
        public string PassportCode { get; set; }
        public string PersonalCode { get; set; }
        public string PersonInfo { get; set; }
        public string ExtraInfo { get; set; }
        public string ScienceWork { get; set; }
        public string PersonNum { get; set; }
        public string FIO { get; set; }
        public string PassportData { get; set; }
        public string EducDocument { get; set; }
        public string HostelFacultyAcr { get; set; }
        public string CountryName { get; set; }
        public string NationalityName { get; set; }
        public string RegionName { get; set; }
        public string HostelFacultyName { get; set; }
        public bool HostelEduc { get; set; }
        public string KladrCode { get; set; }
        public string SNILS { get; set; }
        public string RegionNumber { get; set; }
        public string ForeignNationality { get; set; }
        public Nullable<int> ForeignNationalityId { get; set; }
        public string ForeignCountry { get; set; }
        public Nullable<int> ForeignCountryId { get; set; }
        public bool StartEnglish { get; set; }
        public Nullable<double> EnglishMark { get; set; }
        public bool EgeInSPbgu { get; set; }
        public bool HasTRKI { get; set; }
        public string TRKICertificateNumber { get; set; }
        public bool HasRussianNationality { get; set; }
        public string PassportTypeName { get; set; }
        public string PassportTypeFISName { get; set; }
        public string LanguageName { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<bool> HasOriginals { get; set; }
    }
}
