//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fixieren
    {
        public int Number { get; set; }
        public System.Guid AbiturientId { get; set; }
        public System.Guid FixierenViewId { get; set; }
    
        public virtual Abiturient Abiturient { get; set; }
        public virtual FixierenView FixierenView { get; set; }
    }
}
