//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixierenView
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FixierenView()
        {
            this.Fixieren = new HashSet<Fixieren>();
        }
    
        public System.Guid Id { get; set; }
        public int StudyLevelGroupId { get; set; }
        public int FacultyId { get; set; }
        public int LicenseProgramId { get; set; }
        public int ObrazProgramId { get; set; }
        public int ProfileId { get; set; }
        public int StudyFormId { get; set; }
        public int StudyBasisId { get; set; }
        public bool IsSecond { get; set; }
        public bool IsReduced { get; set; }
        public bool IsParallel { get; set; }
        public bool IsCel { get; set; }
        public Nullable<int> DocNum { get; set; }
        public bool Locked { get; set; }
        public bool IsCrimea { get; set; }
        public bool IsQuota { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fixieren> Fixieren { get; set; }
    }
}
