//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlpAbiturientActionLog
    {
        public string PersonNum { get; set; }
        public string FIO { get; set; }
        public string RegNum { get; set; }
        public int LicenseProgramId { get; set; }
        public string LicenseProgramCode { get; set; }
        public string LicenseProgramName { get; set; }
        public int ObrazProgramId { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public string ObrazProgramName { get; set; }
        public string ProfileName { get; set; }
        public int StudyFormId { get; set; }
        public string StudyFormName { get; set; }
        public int StudyBasisId { get; set; }
        public string StudyBasisName { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public string ActionAuthor { get; set; }
        public string ActionType { get; set; }
        public int FacultyId { get; set; }
        public System.Guid Id { get; set; }
        public int StudyLevelGroupId { get; set; }
    }
}
