//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlpAbiturientActionLog
    {
        public string PersonNum { get; set; }
        public string FIO { get; set; }
        public string RegNum { get; set; }
        public int LicenseProgramId { get; set; }
        public string LicenseProgramCode { get; set; }
        public string LicenseProgramName { get; set; }
        public int ObrazProgramId { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public string ObrazProgramName { get; set; }
        public string ProfileName { get; set; }
        public int StudyFormId { get; set; }
        public string StudyFormName { get; set; }
        public int StudyBasisId { get; set; }
        public string StudyBasisName { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
        public string ActionAuthor { get; set; }
        public string ActionType { get; set; }
        public int FacultyId { get; set; }
        public System.Guid Id { get; set; }
        public int StudyLevelGroupId { get; set; }
    }
}
