//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlpAbiturientProf
    {
        public System.Guid Id { get; set; }
        public Nullable<decimal> Prof { get; set; }
        public Nullable<byte> ProfFiveGrade { get; set; }
    }
}
