//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlpEgeMarkMaxApproved
    {
        public System.Guid PersonId { get; set; }
        public int EgeExamNameId { get; set; }
        public Nullable<System.Guid> EgeMarkId { get; set; }
    }
}
