//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlpStatRatingList
    {
        public System.Guid AbiturientId { get; set; }
        public System.Guid PersonId { get; set; }
        public System.Guid EntryId { get; set; }
        public Nullable<decimal> SUM { get; set; }
        public Nullable<long> Rank { get; set; }
        public int IsCel { get; set; }
    }
}
