//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlpStatistics
    {
        public System.Guid EntryId { get; set; }
        public int StudyLevelGroupId { get; set; }
        public int FacultyId { get; set; }
        public int LicenseProgramId { get; set; }
        public string LicenseProgramCode { get; set; }
        public string LicenseProgramName { get; set; }
        public int ObrazProgramId { get; set; }
        public string ObrazProgramCrypt { get; set; }
        public string ObrazProgramName { get; set; }
        public int ProfileId { get; set; }
        public string ProfileName { get; set; }
        public int StudyFormId { get; set; }
        public string StudyFormName { get; set; }
        public int StudyBasisId { get; set; }
        public string StudyBasisName { get; set; }
        public Nullable<int> KCP { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> CNT { get; set; }
    }
}
