//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class hlpStatRatingList
    {
        public System.Guid AbiturientId { get; set; }
        public System.Guid PersonId { get; set; }
        public System.Guid EntryId { get; set; }
        public Nullable<decimal> SUM { get; set; }
        public Nullable<long> Rank { get; set; }
        public int IsCel { get; set; }
    }
}
