//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class InnerEntryInEntry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InnerEntryInEntry()
        {
            this.ApplicationDetails = new HashSet<ApplicationDetails>();
            this.ApplicationVersionDetails = new HashSet<ApplicationVersionDetails>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid EntryId { get; set; }
        public int ObrazProgramId { get; set; }
        public int ProfileId { get; set; }
        public int KCP { get; set; }
        public Nullable<int> EgeExamNameId { get; set; }
        public Nullable<int> EgeMin { get; set; }
        public Nullable<System.Guid> ParentInnerEntryInEntryId { get; set; }
        public Nullable<System.Guid> ExamInEntryBlockId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationDetails> ApplicationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationVersionDetails> ApplicationVersionDetails { get; set; }
        public virtual Entry Entry { get; set; }
        public virtual SP_ObrazProgram SP_ObrazProgram { get; set; }
        public virtual SP_Profile SP_Profile { get; set; }
        public virtual EgeExamName EgeExamName { get; set; }
        public virtual ExamInEntryBlock ExamInEntryBlock { get; set; }
    }
}
