//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageCertificatesType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public bool BoolType { get; set; }
        public bool ValueType { get; set; }
    }
}
