//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageCertificatesType
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public bool BoolType { get; set; }
        public bool ValueType { get; set; }
    }
}
