//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mark
    {
        public System.Guid Id { get; set; }
        public System.Guid AbiturientId { get; set; }
        public decimal Value { get; set; }
        public Nullable<System.DateTime> PassDate { get; set; }
        public bool IsFromEge { get; set; }
        public bool IsFromOlymp { get; set; }
        public bool IsManual { get; set; }
        public Nullable<System.Guid> ExamVedId { get; set; }
        public Nullable<System.Guid> OlympiadId { get; set; }
        public Nullable<System.Guid> EgeCertificateId { get; set; }
        public Nullable<byte> FiveGradeValue { get; set; }
        public bool IsFromAchievement { get; set; }
        public Nullable<System.Guid> PersonAchievementId { get; set; }
        public System.Guid ExamInEntryBlockUnitId { get; set; }
    
        public virtual Abiturient Abiturient { get; set; }
        public virtual EgeCertificate EgeCertificate { get; set; }
        public virtual ExamInEntryBlockUnit ExamInEntryBlockUnit { get; set; }
        public virtual PersonAchievement PersonAchievement { get; set; }
        public virtual Olympiads Olympiads { get; set; }
    }
}
