//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarkFromAchievement
    {
        public System.Guid Id { get; set; }
        public System.Guid AbiturientId { get; set; }
        public int AchievementTypeId { get; set; }
        public Nullable<System.Guid> OlympiadId { get; set; }
        public int Value { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreateAuthor { get; set; }
    
        public virtual Abiturient Abiturient { get; set; }
        public virtual Olympiads Olympiads { get; set; }
    }
}
