//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympSubjectToExam
    {
        public int Id { get; set; }
        public int OlympSubjectId { get; set; }
        public int ExamId { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual OlympSubject OlympSubject { get; set; }
    }
}
