//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympiadCheckedByRectorat
    {
        public System.Guid OlympId { get; set; }
        public string CheckedUser { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Olympiads Olympiads { get; set; }
    }
}
