//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympiadCheckedByRectorat
    {
        public System.Guid OlympId { get; set; }
        public string CheckedUser { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Olympiads Olympiads { get; set; }
    }
}
