//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympResultToCommonBenefit
    {
        public int Id { get; set; }
        public System.Guid EntryId { get; set; }
        public int OlympTypeId { get; set; }
        public int OlympSubjectId { get; set; }
        public int OlympValueId { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public int OlympLevelId { get; set; }
    
        public virtual Entry Entry { get; set; }
        public virtual OlympSubject OlympSubject { get; set; }
        public virtual OlympType OlympType { get; set; }
        public virtual OlympValue OlympValue { get; set; }
        public virtual OlympLevel OlympLevel { get; set; }
    }
}
