//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympResultToAdditionalMark
    {
        public int Id { get; set; }
        public System.Guid EntryId { get; set; }
        public int OlympLevelId { get; set; }
        public int OlympValueId { get; set; }
        public Nullable<int> ExamId { get; set; }
        public int AdditionalMark { get; set; }
        public decimal MinEge { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public Nullable<int> OlympProfileId { get; set; }
        public Nullable<int> OlympSubjectId { get; set; }
        public Nullable<int> OlympTypeId { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual OlympLevel OlympLevel { get; set; }
        public virtual OlympValue OlympValue { get; set; }
        public virtual OlympType OlympType { get; set; }
        public virtual Entry Entry { get; set; }
    }
}
