//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympResultToMaxMark
    {
        public int Id { get; set; }
        public System.Guid ExamInEntryBlockId { get; set; }
        public System.Guid OlympBookId { get; set; }
        public int OlympValueId { get; set; }
        public int EgeExamId { get; set; }
        public decimal MinEge { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
    }
}
