//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class OlympSubject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OlympSubject()
        {
            this.OlympBook = new HashSet<OlympBook>();
            this.Olympiads = new HashSet<Olympiads>();
            this.OlympSubjectToExam = new HashSet<OlympSubjectToExam>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameDative { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public Nullable<int> ExamId { get; set; }
        public Nullable<bool> IsInVseross { get; set; }
        public Nullable<int> SubjectID_FIS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OlympBook> OlympBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Olympiads> Olympiads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OlympSubjectToExam> OlympSubjectToExam { get; set; }
    }
}
