//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderNumbers
    {
        public System.Guid ProtocolId { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderNum { get; set; }
        public string OrderNumFor { get; set; }
        public Nullable<System.DateTime> OrderDateFor { get; set; }
        public int SignerId { get; set; }
        public System.DateTime ComissionDate { get; set; }
        public string ComissionNumber { get; set; }
    
        public virtual Signer Signer { get; set; }
    }
}
