//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaidData
    {
        public System.Guid Id { get; set; }
        public string DogovorNum { get; set; }
        public System.DateTime DogovorDate { get; set; }
        public int DogovorTypeId { get; set; }
        public Nullable<int> ProrektorId { get; set; }
        public string Qualification { get; set; }
        public string Srok { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateFinish { get; set; }
        public string SumFirstYear { get; set; }
        public int PayPeriodId { get; set; }
        public string SumFirstPeriod { get; set; }
        public string AbitFIORod { get; set; }
        public string Parent { get; set; }
        public string ParentPassport { get; set; }
        public string Customer { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPassport { get; set; }
        public string CustomerPassportAuthor { get; set; }
        public string CustomerLico { get; set; }
        public string CustomerReason { get; set; }
        public string CustomerINN { get; set; }
        public string CustomerRS { get; set; }
        public System.Guid AbiturientId { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public string SumTotal { get; set; }
        public string SrokIndividual { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual DogovorType DogovorType { get; set; }
        public virtual PayPeriod PayPeriod { get; set; }
        public virtual Prorektor Prorektor { get; set; }
        public virtual Abiturient Abiturient { get; set; }
    }
}
