//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonWork
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public string Stage { get; set; }
        public string WorkPlace { get; set; }
        public string WorkProfession { get; set; }
        public string WorkSpecifications { get; set; }
    }
}
