//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person_FetchValues
    {
        public System.Guid Id { get; set; }
        public Nullable<int> CurrentEducationInfoId { get; set; }
        public Nullable<int> EGE_Rus { get; set; }
        public Nullable<int> EGE_Math { get; set; }
        public Nullable<int> EGE_Fiz { get; set; }
        public Nullable<int> EGE_Chem { get; set; }
        public Nullable<int> EGE_Bio { get; set; }
        public Nullable<int> EGE_Ist { get; set; }
        public Nullable<int> EGE_Geogr { get; set; }
        public Nullable<int> EGE_Eng { get; set; }
        public Nullable<int> EGE_Nem { get; set; }
        public Nullable<int> EGE_Fran { get; set; }
        public Nullable<int> EGE_Obsh { get; set; }
        public Nullable<int> EGE_Lit { get; set; }
        public Nullable<int> EGE_Esp { get; set; }
        public Nullable<int> EGE_Inform { get; set; }
    }
}
