//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.Abiturient = new HashSet<Abiturient>();
            this.AttMarks = new HashSet<AttMarks>();
            this.EgeCertificate = new HashSet<EgeCertificate>();
            this.Person_EducationInfo = new HashSet<Person_EducationInfo>();
            this.PersonBenefitDocument = new HashSet<PersonBenefitDocument>();
            this.PersonAchievement = new HashSet<PersonAchievement>();
            this.PersonOtherPassport = new HashSet<PersonOtherPassport>();
            this.PersonNoticies = new HashSet<PersonNoticies>();
            this.ExamsVedHistory = new HashSet<ExamsVedHistory>();
            this.PersonLanguageCertificates = new HashSet<PersonLanguageCertificates>();
        }
    
        public System.Guid Id { get; set; }
        public Nullable<int> Barcode { get; set; }
        public int Num { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string SecondName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public int PassportTypeId { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public string PassportAuthor { get; set; }
        public Nullable<System.DateTime> PassportDate { get; set; }
        public string PassportCode { get; set; }
        public string PersonalCode { get; set; }
        public bool Sex { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public int NationalityId { get; set; }
        public Nullable<int> PersonTypeId { get; set; }
        public Nullable<int> ForeignNationalityId { get; set; }
        public Nullable<int> AdditionalPersonTypeId { get; set; }
        public string SNILS { get; set; }
        public bool HasRussianNationality { get; set; }
        public string Author { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Abiturient> Abiturient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttMarks> AttMarks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EgeCertificate> EgeCertificate { get; set; }
        public virtual PassportType PassportType { get; set; }
        public virtual Person_AdditionalInfo Person_AdditionalInfo { get; set; }
        public virtual Person_Contacts Person_Contacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person_EducationInfo> Person_EducationInfo { get; set; }
        public virtual Country Nationality { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonBenefitDocument> PersonBenefitDocument { get; set; }
        public virtual PersonSportQualification PersonSportQualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonAchievement> PersonAchievement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonOtherPassport> PersonOtherPassport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonNoticies> PersonNoticies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamsVedHistory> ExamsVedHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonLanguageCertificates> PersonLanguageCertificates { get; set; }
    }
}
