//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonChanges
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string Owner { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> FacultyId { get; set; }
    }
}
