//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonLanguageCertificates
    {
        public int Id { get; set; }
        public System.Guid PersonId { get; set; }
        public int LanguageCertificateTypeId { get; set; }
        public string Number { get; set; }
        public Nullable<double> ResultValue { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
