//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonEgeRequest
    {
        public int IntId { get; set; }
        public System.Guid PersonId { get; set; }
        public System.DateTime DateRequest { get; set; }
        public Nullable<System.DateTime> DateAnswer { get; set; }
        public string XMLRequest { get; set; }
        public string XMLAnswer { get; set; }
        public bool IsChecked { get; set; }
    }
}
