//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonNoticies
    {
        public int Id { get; set; }
        public System.Guid PersonId { get; set; }
        public string NoticeText { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string CreateAuthor { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
