//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonBenefitDocument
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public int BenefitDocumentTypeId { get; set; }
        public string Series { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> DisabilityTypeId { get; set; }
        public bool HasOriginals { get; set; }
        public Nullable<System.DateTime> OriginalsDate { get; set; }
        public string Author { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
        public string C_Author { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual BenefitDocumentType BenefitDocumentType { get; set; }
        public virtual Person Person { get; set; }
    }
}
