//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonEgeRequest
    {
        public int IntId { get; set; }
        public System.Guid PersonId { get; set; }
        public System.DateTime DateRequest { get; set; }
        public Nullable<System.DateTime> DateAnswer { get; set; }
        public string XMLRequest { get; set; }
        public string XMLAnswer { get; set; }
        public bool IsChecked { get; set; }
    }
}
