//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonWork
    {
        public System.Guid Id { get; set; }
        public System.Guid PersonId { get; set; }
        public string Stage { get; set; }
        public string WorkPlace { get; set; }
        public string WorkProfession { get; set; }
        public string WorkSpecifications { get; set; }
    }
}
