//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocolNumbers
    {
        public int Id { get; set; }
        public int StudyLevelGroupId { get; set; }
        public int FacultyId { get; set; }
        public long ProtocolNum { get; set; }
        public long MainProtocolNum { get; set; }
    }
}
