//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocolNumbers
    {
        public int Id { get; set; }
        public int StudyLevelGroupId { get; set; }
        public int FacultyId { get; set; }
        public long ProtocolNum { get; set; }
        public long MainProtocolNum { get; set; }
    }
}
