//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protocol
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Protocol()
        {
            this.ProtocolHistory = new HashSet<ProtocolHistory>();
        }
    
        public System.Guid Id { get; set; }
        public int StudyLevelGroupId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> LicenseProgramId { get; set; }
        public int StudyFormId { get; set; }
        public Nullable<int> StudyBasisId { get; set; }
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public int ProtocolTypeId { get; set; }
        public string Reason { get; set; }
        public bool IsOld { get; set; }
        public Nullable<System.Guid> ParentProtocolId { get; set; }
        public bool IsSecond { get; set; }
        public bool IsListener { get; set; }
        public bool IsParallel { get; set; }
        public bool IsReduced { get; set; }
        public bool IsForeign { get; set; }
        public Nullable<int> AdmissionProtocolId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Author { get; set; }
    
        public virtual ProtocolType ProtocolType { get; set; }
        public virtual StudyBasis StudyBasis { get; set; }
        public virtual StudyForm StudyForm { get; set; }
        public virtual SP_Faculty SP_Faculty { get; set; }
        public virtual SP_LicenseProgram SP_LicenseProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProtocolHistory> ProtocolHistory { get; set; }
    }
}
