//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProtocolHistory
    {
        public System.Guid Id { get; set; }
        public System.Guid AbiturientId { get; set; }
        public System.Guid ProtocolId { get; set; }
        public bool Excluded { get; set; }
        public Nullable<System.Guid> ExcludeProtocolId { get; set; }
        public Nullable<int> EntryHeaderId { get; set; }
    
        public virtual Abiturient Abiturient { get; set; }
        public virtual EntryHeader EntryHeader { get; set; }
        public virtual Protocol Protocol { get; set; }
    }
}
