//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class qAbiturient_WhoSetHasOriginals
    {
        public int IntId { get; set; }
        public string UserId { get; set; }
        public System.DateTime ActionTime { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public string FacultyName { get; set; }
        public string FacultyAcronym { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
    }
}
