//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class qAbiturient_WhoSetIsPaid
    {
        public int IntId { get; set; }
        public System.Guid Id { get; set; }
        public string UserId { get; set; }
        public System.DateTime ActionTime { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public string FacultyName { get; set; }
        public string FacultyAcronym { get; set; }
        public Nullable<System.Guid> PersonId { get; set; }
    }
}
