//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class qEntryToCompetitiveGroup
    {
        public System.Guid EntryId { get; set; }
        public System.Guid CompetitiveGroupId { get; set; }
        public string CompetitiveGroupName { get; set; }
    }
}
