//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class qEntryToCompetitiveGroup
    {
        public System.Guid EntryId { get; set; }
        public System.Guid CompetitiveGroupId { get; set; }
        public string CompetitiveGroupName { get; set; }
    }
}
