//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class qMark
    {
        public System.Guid Id { get; set; }
        public System.Guid AbiturientId { get; set; }
        public System.Guid ExamInEntryBlockUnitId { get; set; }
        public decimal Value { get; set; }
        public Nullable<System.DateTime> PassDate { get; set; }
        public bool IsFromEge { get; set; }
        public bool IsFromOlymp { get; set; }
        public bool IsManual { get; set; }
        public Nullable<System.Guid> ExamVedId { get; set; }
        public System.Guid EntryId { get; set; }
        public string ExamName { get; set; }
        public bool IsAdditional { get; set; }
        public bool IsProfil { get; set; }
        public int StudyLevelGroupId { get; set; }
        public int ExamId { get; set; }
        public int ExamNameId { get; set; }
        public string EntranceTestType { get; set; }
        public Nullable<System.Guid> OlympiadId { get; set; }
        public Nullable<System.Guid> EgeCertificateId { get; set; }
        public byte OrderNumber { get; set; }
        public Nullable<byte> FiveGradeValue { get; set; }
        public System.Guid PersonId { get; set; }
        public int StudyBasisId { get; set; }
        public Nullable<System.Guid> ParentExamInEntryBlockId { get; set; }
    }
}
