//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class qObrazProgram
    {
        public string Crypt { get; set; }
        public string Name { get; set; }
        public int LicenseProgramId { get; set; }
        public string LicenseProgramName { get; set; }
        public string Number { get; set; }
        public int Id { get; set; }
    }
}
