//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class qOlympResultToAdditionalMark
    {
        public System.Guid EntryId { get; set; }
        public int ExamId { get; set; }
        public Nullable<int> OlympTypeId { get; set; }
        public int OlympLevelId { get; set; }
        public Nullable<int> OlympProfileId { get; set; }
        public Nullable<int> OlympSubjectId { get; set; }
        public int OlympValueId { get; set; }
        public Nullable<int> EgeExamNameId { get; set; }
        public decimal MinEge { get; set; }
        public int AdditionalMark { get; set; }
    }
}
