//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class qOlympResultToCommonBenefit
    {
        public System.Guid EntryId { get; set; }
        public int ExamId { get; set; }
        public Nullable<int> OlympTypeId { get; set; }
        public int OlympLevelId { get; set; }
        public Nullable<int> OlympProfileId { get; set; }
        public Nullable<int> OlympSubjectId { get; set; }
        public int OlympValueId { get; set; }
        public Nullable<int> EgeExamNameId { get; set; }
        public decimal MinEge { get; set; }
    }
}
