//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class qProtocol
    {
        public System.Guid Id { get; set; }
        public int StudyLevelGroupId { get; set; }
        public Nullable<int> FacultyId { get; set; }
        public Nullable<int> LicenseProgramId { get; set; }
        public int StudyFormId { get; set; }
        public Nullable<int> StudyBasisId { get; set; }
        public string Number { get; set; }
        public System.DateTime Date { get; set; }
        public int ProtocolTypeId { get; set; }
        public string Reason { get; set; }
        public bool IsOld { get; set; }
        public Nullable<System.Guid> ParentProtocolId { get; set; }
        public bool IsSecond { get; set; }
        public bool IsListener { get; set; }
        public bool IsForeign { get; set; }
    }
}
