//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class qStudyLevel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Acronym { get; set; }
        public int LevelGroupId { get; set; }
        public string LevelGroupPrint { get; set; }
        public string FISName { get; set; }
    }
}
