//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class SP_ObrazProgram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SP_ObrazProgram()
        {
            this.Entry = new HashSet<Entry>();
            this.InnerEntryInEntry = new HashSet<InnerEntryInEntry>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string NameEng { get; set; }
        public string Number { get; set; }
        public int LicenseProgramId { get; set; }
        public int FacultyId { get; set; }
        public int ProgramModeId { get; set; }
        public bool IsExpress { get; set; }
        public bool IsOpen { get; set; }
        public string Holder { get; set; }
    
        public virtual SP_LicenseProgram SP_LicenseProgram { get; set; }
        public virtual SP_Faculty SP_Faculty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entry> Entry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InnerEntryInEntry> InnerEntryInEntry { get; set; }
    }
}
