//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriemLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudyLevel()
        {
            this.SP_LicenseProgram = new HashSet<SP_LicenseProgram>();
            this.Entry = new HashSet<Entry>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Acronym { get; set; }
        public int LevelGroupId { get; set; }
        public string LevelGroupPrint { get; set; }
        public string FISName { get; set; }
        public string NameRod { get; set; }
        public string PostName { get; set; }
        public string ClassNum { get; set; }
        public Nullable<int> Duration { get; set; }
    
        public virtual StudyLevelGroup StudyLevelGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SP_LicenseProgram> SP_LicenseProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entry> Entry { get; set; }
    }
}
